# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import faiss_pb2 as faiss__pb2

GRPC_GENERATED_VERSION = '1.64.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in faiss_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class FaissServiceStub(object):
    """FaissService defines the gRPC service for handling vector similarity.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.FindSimilarChunks = channel.unary_unary(
                '/faiss.FaissService/FindSimilarChunks',
                request_serializer=faiss__pb2.SimilarityRequest.SerializeToString,
                response_deserializer=faiss__pb2.SimilarityReply.FromString,
                _registered_method=True)


class FaissServiceServicer(object):
    """FaissService defines the gRPC service for handling vector similarity.
    """

    def FindSimilarChunks(self, request, context):
        """FindSimilarChunks handles the request for finding similar chunks based on a given embedding vector.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FaissServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'FindSimilarChunks': grpc.unary_unary_rpc_method_handler(
                    servicer.FindSimilarChunks,
                    request_deserializer=faiss__pb2.SimilarityRequest.FromString,
                    response_serializer=faiss__pb2.SimilarityReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'faiss.FaissService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('faiss.FaissService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FaissService(object):
    """FaissService defines the gRPC service for handling vector similarity.
    """

    @staticmethod
    def FindSimilarChunks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/faiss.FaissService/FindSimilarChunks',
            faiss__pb2.SimilarityRequest.SerializeToString,
            faiss__pb2.SimilarityReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
