# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: faiss.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x66\x61iss.proto\x12\x05\x66\x61iss\"&\n\x11SimilarityRequest\x12\x11\n\tembedding\x18\x01 \x03(\x02\"8\n\x0fSimilarityReply\x12\x16\n\x0e\x63hunk_contents\x18\x01 \x03(\t\x12\r\n\x05\x65rror\x18\x02 \x01(\t2W\n\x0c\x46\x61issService\x12G\n\x11\x46indSimilarChunks\x12\x18.faiss.SimilarityRequest\x1a\x16.faiss.SimilarityReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'faiss_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SIMILARITYREQUEST']._serialized_start=22
  _globals['_SIMILARITYREQUEST']._serialized_end=60
  _globals['_SIMILARITYREPLY']._serialized_start=62
  _globals['_SIMILARITYREPLY']._serialized_end=118
  _globals['_FAISSSERVICE']._serialized_start=120
  _globals['_FAISSSERVICE']._serialized_end=207
# @@protoc_insertion_point(module_scope)
